# Generated by Django 4.1.5 on 2023-11-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
