# Generated by Django 4.2.7 on 2023-12-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_registration_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
    ]
