# Generated by Django 4.2.7 on 2024-01-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_order_profile_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic', models.ImageField(upload_to='images/profilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.registration')),
            ],
        ),
    ]
